### ISSUE TITLE
Customize distance metrics

### ISSUE THREAD

**Issue by Flowerowl** [bwoneill/pypardis#1]
Hi, is there any idea to customize distance metrics?

**Comment by bwoneill** [comment]
A custom metric can be used by specifying `metric` when initializing the `DBSCAN` object. The metric can be any function that takes two 1-D vectors and returns a number, however the resulting clusters may not be correct. To effectively partition the data into localized chunks, the algorithm assumes that all possible points within distance `d` of an arbitrary point `p` are within the n-cube bounded by the planes normal to `p +/- d * n_i` where `n_i` is the unit vector along each axis (I believe that's the most mathematically complete way of putting it, intuitively it just means that all points within distance `d` of point `p` must fit in a box of length `2d` centered around `p`). This can easily be shown to be true for a Euclidean or Manhattan metric and false for cosine similarity.
In theory, you could change the bounding boxes of `KPartition` to accommodate any metric, however I don't believe it is possible to make an algorithm that will work with all metrics.

**Comment by Flowerowl** [comment]
Thanks a lot! Very inspired. I just want to calculate the distance between the two latitude and longitude.
I'll try.

**Comment by bwoneill** [comment]
Your welcome. Latitude and longitude shouldn't be a problem unless a point is too close to one of the poles. It may be better to convert to Cartesian coordinates just to avoid any potential problems.
