### ISSUE TITLE
pypardis with Python 3

### ISSUE THREAD

**Issue by jocerfranquiz** [bwoneill/pypardis#2]
Hi,
Have you think about upload a python 3 version of your code?

**Comment by bwoneill** [comment]
Hello,
I've pushed an update to the experimental branch for Python 3 support. Unfortunately, my development environment is geared toward Python 2.7 and I'm not very familiar with Python 3. At least it will run my test demo code without error.
I hope that helps.

**Comment by jocerfranquiz** [comment]
Hey @bwoneill, Thanks for answer!! I'll clone the branch and run some tests on it...

**Comment by jocerfranquiz** [comment]
Hi @bwoneill,
I tested `dbscan3.py` and `partition3.py` and it worked well. I added `import numpy as np` on `dbscan3.py` because it wasn't on the file. If you want, I can submit the change.
I use the command `./bin/spark-submit --py-files geometry3.py, aggregator3.py dbscan3.py`.

This is a really nice project! Tell me if you need some help :+1:
